### PR TITLE
Update my_user_config.h for SDM230 device

### PR DESCRIPTION
**Pull request by Noschvie**
## Description:
Change speed parameter to default value of the SDM230 device.

**Related issue (if applicable):** #13443

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.1.0.7.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by dad401** [comment]
The default baudrate (maker setting) for my Eastron SDM230 is 2.400. That's the reason for using this rate also as default in Tasmota.

**Comment by Noschvie** [comment]
@dad401 : Sorry, my device is configured to 9600 baud as shown in the German user guide (v 08/2017).

**Comment by dad401** [comment]
I got my TTL-RAS485 adapter today and I works well at 9.600 baud. So I changed the default rate and a typo. PR can be closed.

**Comment by dad401** [comment]
As stated before.

**Pull request closed without merging**
